### ISSUE TITLE
fonts task doesn't copy font files

### ISSUE THREAD

**Issue by szcze** [Swiip/generator-gulp-angular#849]
Hi, I'm using gulp-angular with bootstrap-sass and noticed that there's no dist/fonts/ directory after the build task. Well, bootstrap-sass-official doesn't declare the font files within the main property, so I added them manually (uugh :/). But still there was no /dist/fonts/.

It seems that 
`return gulp.src($.mainBowerFiles())`
    `  .pipe($.filter('**/*.{eot,svg,ttf,woff,woff2}'))`
    `  .pipe($.flatten())`
    `  .pipe(gulp.dest(path.join(conf.paths.dist, '/fonts/')));`
doesn't filter correctly. Modifying the code to 
`return gulp.src($.mainBowerFiles('**/*.{eot,svg,ttf,woff,woff2}'))`
    `  .pipe($.flatten())`
    `  .pipe(gulp.dest(path.join(conf.paths.dist, '/fonts/')));`
works perfectly fine. So why using $.filter instead of the native filter option of [main-bower-files](https://github.com/ck86/main-bower-files#filter)?

Anyway. Because manually writing to the bower.json is bull**** and since it makes sence that fonts are not declared in the main property, the gulp task 'fonts' should not rely on the bower-main-files, should it? Isn't there a way to scan `/bower_components` for `**/fonts/*.{eot,svg,ttf,woff,woff2}`?

Well I'm not experienced with gulp and I'm certainly not a great programmer, so I'd be happy if some captain could fly by and help out :)

**Comment by mkalpana** [comment]
I ran into the same issue. The bootstrap-sass-official and fontawesome fonts weren't copied over to `/dist/fonts/`. Both, bootstrap-sass-official and fontawesome don't declare the font files in the main property of their bower.json so $.mainBowerFiles() doesn't work.

As a workaround, I had to modify the `gulp/build.js` font task to as follows:

```
gulp.task('fonts', function () {
  return gulp.src('./bower_components/**/*.{eot,svg,ttf,woff,woff2}')
    .pipe($.flatten())
    .pipe(gulp.dest(path.join(conf.paths.dist, '/fonts/')));
});
```

It worked for me. Instead of $.mainBowerFIles() use the path for the `bower_components` directly and you can get past modifying the bower.json manually.

**Comment by Swiip** [comment]
It's all about the `bower.json` from your dependency. Look at https://github.com/Swiip/generator-gulp-angular/blob/master/docs/user-guide.md#bower-dependencies

**Comment by poliveira89** [comment]
@mkalpana the way you are doing it will copy bootstrap font files 2 times, because they have the files duplicated on `fonts/` and on `dist`.

I have this way:

```js
return gulp.src(['./bower_components/bootstrap/fonts/*.{eot,svg,ttf,woff,woff2}', './bower_components/font-awesome/fonts/*.{eot,svg,ttf,woff,woff2}'])
    .pipe($.flatten())
    .pipe(gulp.dest(path.join(conf.paths.dist, '/fonts/')));
```

But does not work when I do `gulp serve` but works with `gulp serve:dist` :/
At this moment, I know that I must look into, BrowserSync options... if I have any update, I will edit this comment...

**Comment by poliveira89** [comment]
My problem with the development version served by `gulp serve` it's because is not overlaying variables.

On `index.less` I have: `@fa-font-path: '../../bower_components/font-awesome/fonts/';`
And the original `variables.less` from FontAwesome there is: `@fa-font-path:        "../fonts";`
After `styles` gulp task being executed the generated CSS contains the wrong path: 
```css
@font-face {
  font-family: 'FontAwesome';
  src: url('../fonts/fontawesome-webfont.eot?v=4.4.0');
  src: url('../fonts/fontawesome-webfont.eot?#iefix&v=4.4.0') format('embedded-opentype'), url('../fonts/fontawesome-webfont.woff2?v=4.4.0') format('woff2'), url('../fonts/fontawesome-webfont.woff?v=4.4.0') format('woff'), url('../fonts/fontawesome-webfont.ttf?v=4.4.0') format('truetype'), url('../fonts/fontawesome-webfont.svg?v=4.4.0#fontawesomeregular') format('svg');
  font-weight: normal;
  font-style: normal;
}
```

I have made a test with LESS, and the problem it's LESS. Did not overlay variables. I created two files `file1.less` and `file2.less`.
```less
// file1.less
@font: #000000;

.stuff {
    background-color: @font;
}
```

```less
// file2.less
@font: #c1c2c3;

@import "file1.less";
```

The compiled CSS file:
```css
.stuff {
  background-color: #000000;
}
```

So, being a problem with LESS maybe I will check in their issues.
Just thought would be nice to share what I found. :smile:
